.TH "CNF" 1 "26 June 2023"
.SH NAME
cnf \- A command not found handler for openSUSE
.SH SYNOPSIS
\fBcnf\fP {binary}
.SH DESCRIPTION
.PP
\fBcnf\fP searches for a package name(s) which installs the binary. It uses
libsolv(3) under the hood. The source of truth of information about
repositories, packages and their content.
.PP
This works with enabled dnf5 or zypper repostiores: the first one found in /usr/bin will be used.
Use dnf5 \-\-refresh makecache or zypper \-\-force refresh to update the metadata used.
.PP
It is typically called through command-not-found mechanism of bash(1) or zsh(1)
or fish(1). This is enabled via installing the cnf-bash or cnf-zsh
packages. Simply typing missing command executes the handler.
.PP
cmake

The program 'cmake' can be found in following packages:
  * cmake-full [ path: /usr/bin/cmake, repository: repo-oss ]
  * cmake-mini [ path: /usr/bin/cmake, repository: repo-oss ]

Try installing with:
    sudo zypper install <selected_package>
.PP
.SH "SEE ALSO"
bash(1), zsh(1), fish(1), libsolv(3)
.SH BUGS
No support for localization other than UTF-8.
.SH "AUTHOR"
.PP
\fBMichal Vyskocil\fR <\&mvyskocil@opensuse\&.org\&>

https://github.com/openSUSE/cnf
