---
name: PR check

on:
  push:
    branches:
      - "main"
  pull_request:
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:

      -
        name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      -
        name: Install libsolv-dev, libclang-dev and cargo
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: libsolv-dev libclang-dev cargo
          version: 1.0

      - uses: Swatinem/rust-cache@v2

      -
        name: Build cnf
        run: cargo build

      -
        name: clippy
        run: cargo clippy --all-targets --all-features
        env:
          RUSTFLAGS: "-Dwarnings"

      -
        name: unit tests
        run: cargo test

      - name: Install cargo-audit
        run: cargo install cargo-audit

      - name: Run cargo audit
        run: cargo audit --deny warnings

      - uses: docker/setup-buildx-action@v2

      -
        name: Build openSUSE Tumbleweed image with zypper
        uses: docker/build-push-action@v4
        with:
          cache-from: type=gha
          cache-to: type=gha,mode=max
          context: test/
          file: test/zypper.dockerfile
          load: true
          push: false
          tags: local/cnf-ci-zypper:latest

      -
        name: Integration test
        run: ./test/bats/bin/bats ./test

